"use client";

import {
  useWidgetProps,
  useMaxHeight,
  useDisplayMode,
  useWidgetState,
} from "../hooks";
import { useEffect, useState, useMemo } from "react";

export default function LoginPage() {
  const toolOutput = useWidgetProps<{ authorizeUrl: string; sessionId: string }>();
  const [state, setState] = useWidgetState<{ authToken?: string }>();

  // Use the sessionId generated by the MCP server
  const sessionId = toolOutput?.sessionId;

  const maxHeight = useMaxHeight() ?? undefined;
  const displayMode = useDisplayMode();

  // Append sessionId to authorizeUrl so the success page knows where to save the token
  const authorizeUrl = useMemo(() => {
    if (!toolOutput?.authorizeUrl || !sessionId) return undefined;
    const url = new URL(toolOutput.authorizeUrl);
    // Many OAuth providers use 'state' for this purpose
    url.searchParams.set("state", sessionId);
    return url.toString();
  }, [toolOutput?.authorizeUrl, sessionId]);

  const handleLogin = () => {
    if (authorizeUrl) {
      const width = 600;
      const height = 600;
      const left = Math.round((window.screen.availWidth - width) / 2);
      const top = Math.round((window.screen.availHeight - height) / 2);

      window.open(
        authorizeUrl,
        "_blank",
        `width=${width},height=${height},left=${left},top=${top}`
      );
    }
  };

  // Poll Redis for the token (Reliable path for cross-origin/sandboxed)
  useEffect(() => {
    if (!sessionId) return;
    
    let interval: NodeJS.Timeout;

    const poll = async () => {
      try {
        const response = await fetch(`/api/auth/poll?sessionId=${sessionId}`);
        const data = await response.json();
        if (data.token) {
          setState({ authToken: data.token });
          clearInterval(interval);
        }
      } catch (error) {
        console.error("Polling error:", error);
      }
    };

    interval = setInterval(poll, 2000);
    return () => clearInterval(interval);
  }, [sessionId, setState]);

  return (
    <div
      className="font-sans grid items-center justify-items-center p-8 pb-20 gap-16 sm:p-20"
      style={{
        maxHeight,
        height: displayMode === "fullscreen" ? maxHeight : undefined,
      }}
    >
      <main className="flex flex-col gap-8 items-center text-center">
        {state?.authToken ? (
          <>
            <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mb-2">
              <svg
                className="w-8 h-8 text-green-600 dark:text-green-400"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <h1 className="text-2xl font-bold">Logged In</h1>
            <p className="text-gray-600 dark:text-gray-400">
              You have successfully authenticated with your account.
            </p>
          </>
        ) : (
          <>
            <h1 className="text-2xl font-bold">Login</h1>
            <p className="text-gray-600 dark:text-gray-400">
              Please click the button below to sign in.
            </p>
            <button
              className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-10 sm:w-auto"
              onClick={handleLogin}
            >
              Login
            </button>
          </>
        )}
      </main>
    </div>
  );
}

