"use client";

import {
  useWidgetProps,
  useWidgetState,
} from "../hooks";
import { useEffect, useState, useMemo } from "react";
import { getUserInfo } from "@/lib/api-service";
import { WidgetState } from "@/app/types/widget-state";

export default function LoginPage() {
  const toolOutput = useWidgetProps<{ authorizeUrl: string; sessionId: string }>();
  const [state, setState] = useWidgetState<WidgetState>();

  // Use the sessionId generated by the MCP server
  const sessionId = toolOutput?.sessionId;

  // Append sessionId to authorizeUrl so the success page knows where to save the token
  const authorizeUrl = useMemo(() => {
    if (!toolOutput?.authorizeUrl || !sessionId) return undefined;
    const url = new URL(toolOutput.authorizeUrl);
    // Many OAuth providers use 'state' for this purpose
    url.searchParams.set("state", sessionId);
    return url.toString();
  }, [toolOutput?.authorizeUrl, sessionId]);

  const handleLogin = () => {
    if (authorizeUrl) {
      const width = 600;
      const height = 600;
      const left = Math.round((window.screen.availWidth - width) / 2);
      const top = Math.round((window.screen.availHeight - height) / 2);

      window.open(
        authorizeUrl,
        "_blank",
        `width=${width},height=${height},left=${left},top=${top}`
      );
    }
  };

  // Poll Redis for the token (Reliable path for cross-origin/sandboxed)
  useEffect(() => {
    if (!sessionId) return;
    
    let interval: NodeJS.Timeout;

    const poll = async () => {
      try {
        const response = await fetch(`/api/auth/poll?sessionId=${sessionId}`);
        const data = await response.json();
        if (data.token) {
          setState({ authToken: data.token, customerId: data.customerId });
          clearInterval(interval);
        }
      } catch (error) {
        console.error("Polling error:", error);
      }
    };

    interval = setInterval(poll, 2000);
    return () => clearInterval(interval);
  }, [sessionId, setState]);

  // Fetch user info when token is available
  useEffect(() => {
    if (state?.authToken && !state?.userInfo) {
      const fetchUserInfo = async () => {
        try {
          const info = await getUserInfo(state.authToken!);
          console.log("nsc-user-info", info);
          console.log("nsc-auth-token", state.authToken);
          console.log("nsc-customer-id", state.customerId);
          // Map PascalCase from API to camelCase for the widget state
          setState((prev) => ({
            ...prev,
            userInfo: {
              email: info.Email || info.email,
              fullName: info.FullName || info.fullName,
              phoneNumber: info.PhoneNumber || info.phoneNumber,
              shippingAddress: info.ShippingAddress || info.shippingAddress,
              billingAddress: info.BillingAddress || info.billingAddress,
            },
          }));
        } catch (error) {
          console.error("Failed to fetch user info:", error);
        }
      };
      fetchUserInfo();
    }
  }, [state?.authToken, state?.userInfo, setState]);

  return (
    <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center p-5 gap-16">
      <main className="flex flex-col gap-8 row-start-2 items-center text-center">
        {state?.authToken ? (
          <>
            <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mb-2">
              <svg
                className="w-8 h-8 text-green-600 dark:text-green-400"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <h1 className="text-2xl font-bold">Logged In</h1>
            {state?.userInfo && (
              <div className="mt-2 text-center flex flex-col gap-1">
                <p className="text-lg font-bold text-foreground">
                  {state.userInfo.fullName}
                </p>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  {state.userInfo.email}
                </p>
                {state.userInfo.phoneNumber && (
                  <p className="text-xs text-gray-500">
                    {state.userInfo.phoneNumber}
                  </p>
                )}
                {state.userInfo.shippingAddress && (
                  <p className="text-xs text-gray-500">
                    Shipping Address: {state.userInfo.shippingAddress}
                  </p>
                )}
                {state.userInfo.billingAddress && (
                  <p className="text-xs text-gray-500">
                    Billing Address: {state.userInfo.billingAddress}
                  </p>
                )}
              </div>
            )}
            <p className="text-gray-600 dark:text-gray-400 mt-4">
              You have successfully authenticated with your account.
            </p>
          </>
        ) : (
          <>
            <h1 className="text-2xl font-bold">Login</h1>
            <p className="text-gray-600 dark:text-gray-400">
              Please click the button below to sign in.
            </p>
            <button
              className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-10 sm:w-auto"
              onClick={handleLogin}
            >
              Login
            </button>
          </>
        )}
      </main>
    </div>
  );
}

